FROM mariadb:10.6.7

COPY src/seedDb.sh /docker-entrypoint-initdb.d/

ARG database="database_2023-10-20_14-58-49-0500(CDT).tar.gz"

RUN apt-get update && apt-get install -y \
	curl \
	&& rm -rf /var/lib/apt/lists/* \
	&& mkdir -p /var/lib/mysql_backup \
	&& curl -SL "https://wikimedia.github.io/pixel-seed-data/$database" \
	| tar -C /var/lib/mysql_backup --strip-components=3 -xzv \
	&& chown mysql:mysql /var/lib/mysql_backup
