FROM --platform=linux/amd64 pixel-base-regression:latest

ARG BACKSTOPJS_VERSION

ENV BACKSTOPJS_VERSION=$BACKSTOPJS_VERSION

RUN set -ex && \
    sudo npm install -g --unsafe-perm=true --allow-root backstopjs@${BACKSTOPJS_VERSION};

WORKDIR /src

ENTRYPOINT ["backstop"]
