FROM --platform=linux/amd64 pixel-base-regression:latest

ARG PA11Y_VERSION

ENV PA11Y_VERSION=$PA11Y_VERSION

RUN set -ex && \
    sudo npm install -g --unsafe-perm=true --allow-root pa11y@${PA11Y_VERSION} \
    mustache node-fetch@2;

ENTRYPOINT ["node", "src/a11y/runA11yTests.js"]
