FROM mariadb:10.11.8

COPY src/seedDb.sh /docker-entrypoint-initdb.d/

ARG database="database_2025-02-12_16-49-46-0600(CST).tar.gz"

RUN apt-get update && apt-get install -y \
	curl \
	&& rm -rf /var/lib/apt/lists/* \
	&& mkdir -p /var/lib/mysql_backup \
	&& curl --compressed --retry 5 --retry-delay 5 --retry-max-time 120 -SL "https://wikimedia.github.io/pixel-seed-data/$database" \
	| tar -C /var/lib/mysql_backup --strip-components=3 -xzv \
	&& chown mysql:mysql /var/lib/mysql_backup
