FROM node:21-alpine3.18

RUN apk add --no-cache git && \
    npm install -g auto-changelog && \
    git config --global --add safe.directory /app

WORKDIR /app

VOLUME ["/app"]

CMD ["auto-changelog"]

